feat: add transformations for 2.0->ATT
BuildingSync/transformations pull request #2
Opened 2020-04-20 19:52 UTC by macintoshpie

This adds another script for tweaking the 2.0 files to be slightly more favorable for Audit Template Tool.

NOTE:
This DOES NOT produce files that are able to round trip with ATT. In other words, the files this produce are not 100% compatible with ATT as there are discrepancies between the way ATT and BRICR/SEED currently use Scenarios. Thus, when one of the resulting files is imported then exported from ATT it will likely still lose some data.

2020-04-20 23:18 UTC, corymosiman12 requested changes

2020-04-20 23:18 UTC, corymosiman12 commented on BRICR-to-v2.0/fix_ATT.py
> +    gas_savings_xpath = '/auc:BuildingSync/auc:Facilities/auc:Facility/auc:Reports/auc:Report/auc:Scenarios/auc:Scenario/auc:ScenarioType/auc:PackageOfMeasures/auc:AnnualSavingsByFuels/auc:AnnualSavi
Just make sure converting from kbtu...I know it's probably all the same but just to be safe
```python
electricity_savings_xpath = .../auc:ResourceUnits[text()='kBtu']
gas_savings_xpath = .../auc:ResourceUnits[text()='kBtu']
```

2020-04-20 23:18 UTC, corymosiman12 commented on BRICR-to-v2.0/fix_ATT.py
> +    measure_udf_raw = [["Rebate Available", "true"]]
I would change to false

2020-04-21 17:41 UTC, macintoshpie commented on BRICR-to-v2.0/fix_ATT.py
> +    gas_savings_xpath = '/auc:BuildingSync/auc:Facilities/auc:Facility/auc:Reports/auc:Report/auc:Scenarios/auc:Scenario/auc:ScenarioType/auc:PackageOfMeasures/auc:AnnualSavingsByFuels/auc:AnnualSavi
Good catch. Also TIL about `text()`

2020-04-21 18:00 UTC, corymosiman12 approved these changes

2020-04-21 18:01 UTC, merged